#server:
#  port: 8080
#spring:#  datasource:#    url: jdbc:mysql://localhost:3307/examination
#    username: examuser
#    password: Kanhaiya@123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    #  jpa:#    properties:#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        
#    hibernate:#      ddl-auto: update
#    show-sql: true
#        #       # #      